IF(NOT EXISTS(SELECT *
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE SCHEMA_NAME = 'Rights'))
BEGIN
	EXEC ('CREATE SCHEMA Rights;');
	GRANT INSERT ON SCHEMA :: Rights TO dbo; 
END

SELECT *
FROM INFORMATION_SCHEMA.TABLES